[tool.ruff]
line-length = 100
target-version = "py310"

[tool.ruff.lint]
# Keep the same rule sets you selected earlier
select = ["E","F","I","UP","B","ARG","C4"]
# No ignore necessary once tkinter is refactored
ignore = []
