[tool.black]
line-length = 100
target-version = ["py310"]

[tool.ruff]
line-length = 100
target-version = "py310"
# Common, useful rule sets
select = ["E","F","I","UP","B","ARG","C4"]
ignore = ["E501"]  # handled by black
